USE mininet;

CREATE TABLE Person (
   id VARCHAR(20) NOT NULL PRIMARY KEY,
   username VARCHAR(30) NOT NULL,
   password VARCHAR(40),
   avatar BLOB,
   gender ENUM ('Female', 'Male'),
   birthdate DATE NOT NULL,
   email BLOB
) ENGINE=InnoDB;

CREATE TABLE PersonLocation (
   pid VARCHAR(20) NOT NULL PRIMARY KEY,
   longitude DEC(10,4) NOT NULL,
   latitude DEC(10,4) NOT NULL,
   CONSTRAINT FOREIGN KEY (pid) REFERENCES Person(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE GCMRegistration (
   pid VARCHAR(20) NOT NULL PRIMARY KEY,
   regid BLOB,
   CONSTRAINT FOREIGN KEY (pid) REFERENCES Person(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE Employer (
   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(20) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE Employment (
   pid VARCHAR(20) NOT NULL,
   eid INT NOT NULL,
   PRIMARY KEY(pid, eid),
   CONSTRAINT FOREIGN KEY (pid) REFERENCES Person(id) ON DELETE CASCADE ON UPDATE CASCADE,
   CONSTRAINT FOREIGN KEY (eid) REFERENCES Employer(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE School (
   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(20) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE Education (
   pid VARCHAR(20) NOT NULL,
   sid INT NOT NULL,
   PRIMARY KEY(pid, sid),
   CONSTRAINT FOREIGN KEY (pid) REFERENCES Person(id) ON DELETE CASCADE ON UPDATE CASCADE,
   CONSTRAINT FOREIGN KEY (sid) REFERENCES School(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE SocialNetwork (
   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(20) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE PersonSocialNetwork (
   pid VARCHAR(20) NOT NULL,
   snid INT NOT NULL,
   snuserid VARCHAR(20) NOT NULL,
   PRIMARY KEY(pid, snid),
   CONSTRAINT FOREIGN KEY (pid) REFERENCES Person(id) ON DELETE CASCADE ON UPDATE CASCADE,
   CONSTRAINT FOREIGN KEY (snid) REFERENCES SocialNetwork(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE Interest (
   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(30) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE PersonInterest (
   pid VARCHAR(20) NOT NULL,
   iid INT NOT NULL,
   PRIMARY KEY(pid, iid),
   CONSTRAINT FOREIGN KEY (pid) REFERENCES Person(id) ON DELETE CASCADE ON UPDATE CASCADE,
   CONSTRAINT FOREIGN KEY (iid) REFERENCES Interest(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE Friend (
   pid1 VARCHAR(20) NOT NULL,
   pid2 VARCHAR(20) NOT NULL,
   PRIMARY KEY(pid1, pid2),
   CONSTRAINT FOREIGN KEY (pid1) REFERENCES Person(id) ON DELETE CASCADE ON UPDATE CASCADE,
   CONSTRAINT FOREIGN KEY (pid2) REFERENCES Person(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE Blocked (
   blockerid VARCHAR(20) NOT NULL,
   blockeeid VARCHAR(20) NOT NULL,
   PRIMARY KEY(blockerid, blockeeid),
   CONSTRAINT FOREIGN KEY (blockerid) REFERENCES Person(id) ON DELETE CASCADE ON UPDATE CASCADE,
   CONSTRAINT FOREIGN KEY (blockeeid) REFERENCES Person(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE Privacy (
   pid VARCHAR(20) NOT NULL PRIMARY KEY,
   level ENUM('Everyone', 'Friends', 'Me') NOT NULL DEFAULT 'Everyone',
   basic BOOL NOT NULL DEFAULT TRUE,
   location BOOL NOT NULL DEFAULT TRUE,
   detailed BOOL NOT NULL DEFAULT TRUE,
   CONSTRAINT FOREIGN KEY (pid) REFERENCES Person(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;
